Add compact block statistics to Debug window UI
ptschip/BitcoinUnlimited pull request #4
Opened 2019-01-31 05:54 UTC by Justaphf

Simply adds the block propagation statistics to the Debug window UI, the same as the XThin and Graphene statistics.

This is based off of what is already being recorded for the compact block statistics as that work was already implemented as part of the parent PR.

NOTE: The UI matches the RPC call, but I think there is something wrong in the statistics collection now.  I've had a build up and running for only ~2 hours, but I'm now seeing a mismatch in the number of total (all time) send/receive blocks of each type and the 24-hour statistics.  These should be identical for the first 24-hours for each propagation method, however the 24-hour totals are lower than the overall totals.
![image](https://user-images.githubusercontent.com/6402604/52033117-cf96de00-24f1-11e9-90eb-06f2c5a47f9b.png)

Not sure when this issue was introduced, but am looking into it.  I'll try looking at a build without the compact blocks PR as well to see if it's localized to this PR.

2019-01-31 13:39 UTC, ptschip requested changes
NIT:  I think it would be better to align the ordering of what's on the debug window to what you see from the getnetworkinfo() rpc.  In other words have either compact blocks come after graphene (on the debug ui) or probably easier to do, move up compact blocks to second place in the getnetworkinfo() rpc.

2019-02-01 04:31 UTC, Justaphf commented
I'm updating the RPC call order as suggested.  I intentionally put XThin and Compact above Graphene in the UI as those are similar concepts/efficiencies while Graphene is the next step up.  I just didn't notice the order discrepancy in the output of `getnetworkinfo` RPC.

I also noticed that the help message was out of date (missing some entries, not just the new CB stats) so am also updating that.  Will push up after a quick implementation test locally.

2019-02-01 14:56 UTC, ptschip approved these changes

2019-02-01 14:56 UTC, merged

2019-02-01 14:56 UTC, ptschip commented
merged